#!/usr/bin/env node
/**
 * Restore proto3 explicit presence in the stubs generated by @ngx-grpc/protoc-gen-ng.
 *
 * Usage: node fix-proto3-optional-presence.ts <descriptor_set_file> <stubs_directory>
 *
 * WHY
 * ---
 * `protoc-gen-ng` emits the same code for a field declared `optional bool x = 5;` and for a
 * plain `bool x = 5;`:
 *
 *   refineValues:            _instance.x = _instance.x || false;
 *   serializeBinaryToWriter: if (_instance.x) { _writer.writeBool(5, _instance.x); }
 *
 * For a plain proto3 field that is correct - a zero value is not on the wire. For a field with
 * explicit presence it destroys the distinction the `optional` keyword exists to express, twice
 * over: `refineValues` (called from the constructor and after every read) rewrites "unset" into
 * the zero value, and the truthiness guard then refuses to write that zero value. The zero value
 * of such a field is therefore unreachable from Angular - `false`, `0` and `""` produce no bytes,
 * so the server applies its own default instead. An enum whose first value is the meaningful one
 * (`CallView.MINIMUM = 0`) cannot be requested at all.
 *
 * WHY A DESCRIPTOR AND NOT A TEXT SUBSTITUTION
 * -------------------------------------------
 * Because the two cases above are byte-identical in the generated output, no pattern over the
 * `.ts` can tell them apart, and rewriting both would be wire-breaking: a plain proto3 scalar
 * MUST stay unwritten at its zero value. `protoc` is the only component that still knows the
 * difference, and it records it as `proto3_optional` on the `FieldDescriptorProto`. The
 * compile pipeline captures a descriptor set BEFORE it strips the `optional` keyword from the
 * protos (see compile-proto-2-stubs.sh), and this codemod rewrites exactly the (message, field)
 * pairs that descriptor marks. Every other byte of the generated tree is left alone.
 *
 * WHAT IS REWRITTEN
 * -----------------
 * Per presence-bearing field, in the class whose `static id` matches the message's fully
 * qualified proto name:
 *
 *   1. the `refineValues` coercion is DELETED, so "the caller said nothing" survives as
 *      `undefined` instead of becoming the zero value. Fixing only the writer would fix
 *      nothing: the coercion runs first, from the constructor.
 *   2. the writer guard becomes a presence test (`!== undefined && !== null`) instead of a
 *      truthiness test, so an explicit zero value is serialized.
 *
 * The READER (`deserializeBinaryFromReader`) is deliberately NOT touched. Its per-field branch
 * already runs only when the field is on the wire; presence was destroyed on the read path
 * solely by the `refineValues` call at the end of it, which step 1 already fixes. A field absent
 * from the wire now stays `undefined` after a read, which is what presence means.
 *
 * Message-typed `optional` fields are skipped: a message is either an object or absent, so
 * `if (_instance.x)` is already an exact presence test and `_instance.x = _instance.x || undefined`
 * is already a no-op. Rewriting them would add diff noise and no behaviour.
 *
 * The declared TypeScript types are left alone as well. The generated type layer never modelled
 * presence - `AsObject` requires every field and the constructor assigns a `RecursivePartial`
 * value straight into a non-optional setter - so widening one getter to `T | undefined` would be
 * inconsistent with the rest of the emitted code and a breaking change for every consumer
 * compiled with `strictNullChecks`. Presence is observable at runtime (`=== undefined`).
 *
 * Anything unexpected is a hard failure, never a silent skip: a message the descriptor knows and
 * the generated tree does not, or a field whose generated shape does not match the two patterns
 * above (a future protoc-gen-ng release), aborts the build rather than shipping a client that
 * silently drops values.
 */

const fs: typeof import('fs') = require('fs');
const path: typeof import('path') = require('path');

/** Column at which protoc-gen-ng's own prettier pass wraps, so rewrites keep its formatting. */
const PRINT_WIDTH = 80;

// ---------------------------------------------------------------------------------------------
// Minimal FileDescriptorSet reader
//
// Deliberately dependency-free: this runs inside the compiler image AND on a developer/CI host
// (the bats suite drives the pipeline with a PATH-mocked protoc), and `google-protobuf` is a
// devDependency of the image, not something either host is guaranteed to have. Only the handful
// of descriptor.proto fields needed to answer "does this field have explicit presence" is
// decoded; everything else is skipped by wire type.
// ---------------------------------------------------------------------------------------------

const WIRE_VARINT = 0;
const WIRE_FIXED64 = 1;
const WIRE_LENGTH_DELIMITED = 2;
const WIRE_FIXED32 = 5;

// FileDescriptorSet
const SET_FILE = 1;
// FileDescriptorProto
const FILE_PACKAGE = 2;
const FILE_MESSAGE_TYPE = 4;
// DescriptorProto
const MESSAGE_NAME = 1;
const MESSAGE_FIELD = 2;
const MESSAGE_NESTED_TYPE = 3;
// FieldDescriptorProto
const FIELD_NAME = 1;
const FIELD_NUMBER = 3;
const FIELD_TYPE = 5;
const FIELD_PROTO3_OPTIONAL = 17;
// FieldDescriptorProto.Type
const TYPE_GROUP = 10;
const TYPE_MESSAGE = 11;

interface ProtoRecord {
  readonly fieldNumber: number;
  /** Payload of a length-delimited record; empty for every other wire type. */
  readonly data: Uint8Array;
  /** Decoded value of a varint record; 0 for every other wire type. */
  readonly varint: number;
}

function readVarint(buffer: Uint8Array, offset: number): [value: number, next: number] {
  let value = 0;
  let shift = 1;
  let position = offset;
  while (position < buffer.length) {
    const byte: number = buffer[position];
    position += 1;
    value += (byte & 0x7f) * shift;
    if ((byte & 0x80) === 0) {
      return [value, position];
    }
    shift *= 128;
  }
  throw new Error(`truncated varint at offset ${offset}`);
}

function* readRecords(buffer: Uint8Array): Generator<ProtoRecord> {
  let offset = 0;
  while (offset < buffer.length) {
    const [key, afterKey] = readVarint(buffer, offset);
    const fieldNumber = Math.floor(key / 8);
    const wireType = key % 8;
    if (wireType === WIRE_VARINT) {
      const [value, next] = readVarint(buffer, afterKey);
      offset = next;
      yield { fieldNumber, data: new Uint8Array(0), varint: value };
    } else if (wireType === WIRE_LENGTH_DELIMITED) {
      const [length, afterLength] = readVarint(buffer, afterKey);
      const end = afterLength + length;
      if (end > buffer.length) {
        throw new Error(`truncated length-delimited record for field ${fieldNumber}`);
      }
      offset = end;
      yield { fieldNumber, data: buffer.subarray(afterLength, end), varint: 0 };
    } else if (wireType === WIRE_FIXED64) {
      offset = afterKey + 8;
      yield { fieldNumber, data: new Uint8Array(0), varint: 0 };
    } else if (wireType === WIRE_FIXED32) {
      offset = afterKey + 4;
      yield { fieldNumber, data: new Uint8Array(0), varint: 0 };
    } else {
      throw new Error(`unsupported wire type ${wireType} for field ${fieldNumber}`);
    }
  }
}

function decodeString(data: Uint8Array): string {
  return Buffer.from(data).toString('utf8');
}

/** A field the descriptor marks as having explicit presence, in one message. */
interface PresenceField {
  readonly protoName: string;
  readonly fieldNumber: number;
}

/** Fully qualified proto message name -> its presence-bearing scalar/enum fields. */
type PresenceIndex = Map<string, PresenceField[]>;

interface DescriptorSummary {
  readonly index: PresenceIndex;
  readonly fileCount: number;
  /** Message-typed `optional` fields, counted but not rewritten (see the header comment). */
  readonly messageTypedCount: number;
}

function collectMessage(
  data: Uint8Array,
  scope: string,
  index: PresenceIndex,
  counters: { messageTyped: number }
): void {
  let messageName = '';
  const fields: Uint8Array[] = [];
  const nested: Uint8Array[] = [];
  for (const record of readRecords(data)) {
    if (record.fieldNumber === MESSAGE_NAME) {
      messageName = decodeString(record.data);
    } else if (record.fieldNumber === MESSAGE_FIELD) {
      fields.push(record.data);
    } else if (record.fieldNumber === MESSAGE_NESTED_TYPE) {
      nested.push(record.data);
    }
  }

  const fullName = scope === '' ? messageName : `${scope}.${messageName}`;
  const presenceFields: PresenceField[] = [];
  for (const field of fields) {
    let protoName = '';
    let fieldNumber = 0;
    let fieldType = 0;
    let proto3Optional = false;
    for (const record of readRecords(field)) {
      if (record.fieldNumber === FIELD_NAME) {
        protoName = decodeString(record.data);
      } else if (record.fieldNumber === FIELD_NUMBER) {
        fieldNumber = record.varint;
      } else if (record.fieldNumber === FIELD_TYPE) {
        fieldType = record.varint;
      } else if (record.fieldNumber === FIELD_PROTO3_OPTIONAL) {
        proto3Optional = record.varint !== 0;
      }
    }
    if (!proto3Optional) {
      continue;
    }
    if (fieldType === TYPE_MESSAGE || fieldType === TYPE_GROUP) {
      counters.messageTyped += 1;
      continue;
    }
    presenceFields.push({ protoName, fieldNumber });
  }

  if (presenceFields.length > 0) {
    index.set(fullName, presenceFields);
  }
  for (const nestedMessage of nested) {
    collectMessage(nestedMessage, fullName, index, counters);
  }
}

function readDescriptorSet(descriptorPath: string): DescriptorSummary {
  const buffer = new Uint8Array(fs.readFileSync(descriptorPath));
  const index: PresenceIndex = new Map();
  const counters = { messageTyped: 0 };
  let fileCount = 0;

  for (const fileRecord of readRecords(buffer)) {
    if (fileRecord.fieldNumber !== SET_FILE) {
      continue;
    }
    fileCount += 1;
    let packageName = '';
    const messages: Uint8Array[] = [];
    for (const record of readRecords(fileRecord.data)) {
      if (record.fieldNumber === FILE_PACKAGE) {
        packageName = decodeString(record.data);
      } else if (record.fieldNumber === FILE_MESSAGE_TYPE) {
        messages.push(record.data);
      }
    }
    for (const message of messages) {
      collectMessage(message, packageName, index, counters);
    }
  }

  return { index, fileCount, messageTypedCount: counters.messageTyped };
}

// ---------------------------------------------------------------------------------------------
// Rewriting the generated stubs
// ---------------------------------------------------------------------------------------------

/**
 * The generated property name is read back out of the writer statement rather than derived from
 * the proto field name, so no assumption about protoc-gen-ng's camel-casing can go wrong: the
 * field NUMBER is the join key, and it is unambiguous within a message.
 */
function writerPatternFor(fieldNumber: number): RegExp {
  return new RegExp(
    `^([ \\t]*)if \\(_instance\\.([A-Za-z0-9_$]+)\\) \\{\\n` +
      `(\\s*_writer\\.write[A-Za-z0-9]+\\(\\s*${fieldNumber},)`,
    'm'
  );
}

function refinePatternFor(property: string): RegExp {
  const name = `_instance\\.${property}`;
  return new RegExp(`^[ \\t]*${name} =\\s*(?:\\n\\s*)?${name} \\|\\| [^;]*;[ \\t]*\\n`, 'm');
}

function countMatches(text: string, pattern: RegExp): number {
  const globalPattern = new RegExp(pattern.source, `${pattern.flags}g`);
  return text.match(globalPattern)?.length ?? 0;
}

function presenceGuard(indent: string, property: string): string {
  const test = `_instance.${property} !== undefined && _instance.${property} !== null`;
  const singleLine = `${indent}if (${test}) {`;
  if (singleLine.length <= PRINT_WIDTH) {
    return singleLine;
  }
  return (
    `${indent}if (\n` +
    `${indent}  _instance.${property} !== undefined &&\n` +
    `${indent}  _instance.${property} !== null\n` +
    `${indent}) {`
  );
}

function fail(messageId: string, field: PresenceField, reason: string): never {
  throw new Error(
    `${messageId}.${field.protoName} (field ${field.fieldNumber}): ${reason}. ` +
      'The generated code no longer has the shape this codemod rewrites - most likely ' +
      '@ngx-grpc/protoc-gen-ng changed its output. Refusing to ship a client that silently ' +
      'drops explicitly set zero values.'
  );
}

/**
 * Rewrite one message class. `region` runs from the class's `static id` line to the next one,
 * which covers all of its members; the two statement shapes matched here occur nowhere else.
 */
function rewriteClassRegion(region: string, messageId: string, fields: PresenceField[]): string {
  let text = region;
  for (const field of fields) {
    const writerPattern = writerPatternFor(field.fieldNumber);
    const writerMatches = countMatches(text, writerPattern);
    if (writerMatches !== 1) {
      fail(messageId, field, `expected 1 writer guard, found ${writerMatches}`);
    }
    const writerMatch = writerPattern.exec(text);
    if (writerMatch === null) {
      fail(messageId, field, 'writer guard vanished between counting and matching');
    }
    const indent: string = writerMatch[1];
    const property: string = writerMatch[2];
    const writeCall: string = writerMatch[3];
    // A replacer FUNCTION returns its string verbatim - no "$" substitution to escape.
    text = text.replace(writerPattern, () => `${presenceGuard(indent, property)}\n${writeCall}`);

    const refinePattern = refinePatternFor(property);
    const refineMatches = countMatches(text, refinePattern);
    if (refineMatches !== 1) {
      fail(messageId, field, `expected 1 refineValues coercion of "${property}", found ${refineMatches}`);
    }
    text = text.replace(refinePattern, '');
  }
  return text;
}

const CLASS_ID_PATTERN = /^[ \t]*static id = '([A-Za-z0-9_.]+)';$/gm;

function rewriteStubFile(
  source: string,
  index: PresenceIndex,
  rewrittenMessages: Set<string>
): { text: string; fieldCount: number } {
  const starts: { messageId: string; offset: number }[] = [];
  CLASS_ID_PATTERN.lastIndex = 0;
  let match: RegExpExecArray | null = CLASS_ID_PATTERN.exec(source);
  while (match !== null) {
    starts.push({ messageId: match[1], offset: match.index });
    match = CLASS_ID_PATTERN.exec(source);
  }
  if (starts.length === 0) {
    return { text: source, fieldCount: 0 };
  }

  let text = source.slice(0, starts[0].offset);
  let fieldCount = 0;
  for (let i = 0; i < starts.length; i += 1) {
    const end = i + 1 < starts.length ? starts[i + 1].offset : source.length;
    const region = source.slice(starts[i].offset, end);
    const fields = index.get(starts[i].messageId);
    if (fields === undefined) {
      text += region;
      continue;
    }
    text += rewriteClassRegion(region, starts[i].messageId, fields);
    fieldCount += fields.length;
    rewrittenMessages.add(starts[i].messageId);
  }
  return { text, fieldCount };
}

function collectStubFiles(directory: string): string[] {
  const found: string[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const full = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      found.push(...collectStubFiles(full));
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      found.push(full);
    }
  }
  return found.sort();
}

function main(argv: string[]): void {
  const [descriptorPath, stubsDirectory] = argv;
  if (descriptorPath === undefined || stubsDirectory === undefined) {
    throw new Error('usage: fix-proto3-optional-presence.ts <descriptor_set_file> <stubs_directory>');
  }
  if (!fs.existsSync(descriptorPath)) {
    throw new Error(`descriptor set "${descriptorPath}" does not exist`);
  }
  if (!fs.existsSync(stubsDirectory)) {
    throw new Error(`stubs directory "${stubsDirectory}" does not exist`);
  }

  const summary = readDescriptorSet(descriptorPath);
  // An empty descriptor is a broken inspection, not the answer "nothing has presence": it would
  // silently rewrite nothing and report success.
  if (summary.fileCount === 0) {
    throw new Error(`descriptor set "${descriptorPath}" describes no .proto file`);
  }

  const stubFiles = collectStubFiles(stubsDirectory);
  if (stubFiles.length === 0) {
    throw new Error(`no .ts stubs found under "${stubsDirectory}"`);
  }

  const rewrittenMessages = new Set<string>();
  let rewrittenFields = 0;
  let rewrittenFiles = 0;
  for (const file of stubFiles) {
    const source = fs.readFileSync(file, 'utf8');
    const result = rewriteStubFile(source, summary.index, rewrittenMessages);
    if (result.text !== source) {
      fs.writeFileSync(file, result.text);
      rewrittenFiles += 1;
    }
    rewrittenFields += result.fieldCount;
  }

  const missing = [...summary.index.keys()].filter((messageId) => !rewrittenMessages.has(messageId));
  if (missing.length > 0) {
    throw new Error(
      `the descriptor marks explicit presence in ${missing.length} message(s) that no generated ` +
        `stub declares: ${missing.slice(0, 10).join(', ')}${missing.length > 10 ? ', ...' : ''}`
    );
  }

  console.log(
    `proto3 optional presence: rewrote ${rewrittenFields} field(s) in ${rewrittenMessages.size} ` +
      `message(s) across ${rewrittenFiles} of ${stubFiles.length} stub file(s) ` +
      `(${summary.fileCount} .proto file(s) inspected; ` +
      `${summary.messageTypedCount} message-typed optional field(s) already have presence).`
  );
}

try {
  main(process.argv.slice(2));
} catch (error) {
  console.error(`ERROR: fix-proto3-optional-presence: ${(error as Error).message}`);
  process.exit(1);
}
