#!/usr/bin/env bats
# The angular orchestrator's output-volume clean: WHEN it runs, and WHAT it is able to reach.
#
# Every angular client generates with
#   docker run -v ${PWD}:/input-volume -v ${PWD}/..:/output-volume ondewo-angular-proto-compiler ...
# from its `src` directory, so the OUTPUT volume is the client REPOSITORY ROOT and the mounted
# INPUT volume is the `src` directory one level inside it. The clean removes fourteen entries
# from that repository root - package.json, public-api.ts, public-api.d.ts, npm/, api/ and the
# bundle directories - i.e. the client's entire previously generated library.
#
# Two things about that were wrong:
#
#   * it ran BEFORE the input requirements were checked, so every abort path (a missing
#     README.md, a protos directory that does not exist, a typo'd target sub-directory, a
#     failing library build) deleted the existing library first and then exited non-zero,
#     leaving the repository worse than before the run and with nothing to restore from;
#
#   * it ran with the working directory changed to the output volume and one of its entries was
#     the NESTED path `src/node_modules` - which in the layout above resolves into the mounted
#     input volume, the tree this image copies to $TEMP_SRC_DIRECTORY precisely so that it never
#     modifies it, and the very folder the clean's own message says it preserves.
#
# The fix moves the clean to the commit point (after compilation, immediately before the results
# are copied back) and deletes only ${OUTPUT_VOLUME_FS:?}-rooted top-level names. The cases below
# pin both halves: every abort leaves the previous library byte-intact, a successful run still
# sweeps the stale one, and the mounted input volume is not modified at all.

load 'helpers/setup'

setup() {
  common_setup
  export PROTOC_MOCK_LOG="$SANDBOX/protoc.log"
  export NPM_MOCK_LOG="$SANDBOX/npm.log"
  ORCH="$REPO_ROOT/angular/image-data/compile-proto-2-angular.sh"
  # the client layout: output volume = repository root, input volume = its src/ directory
  REPO="$SANDBOX/client"
  OUT="$REPO"
  IN="$REPO/src"
  mkdir -p "$IN/ondewo-nlu-api/ondewo"
  printf 'syntax = "proto3";\nmessage T {\n  optional bool flag = 1;\n}\n' \
    > "$IN/ondewo-nlu-api/ondewo/test.proto"
}
teardown() { common_teardown; }

# Copy the angular image-data into the sandbox (nothing is written into the repo tree), cd there
# (the orchestrator invokes its siblings as ./x.sh) and point the container paths at the sandbox.
stage() {
  cp -r "$REPO_ROOT/angular/image-data" "$SANDBOX/image-data"
  cd "$SANDBOX/image-data"
  export IMAGE_DATA_DIRECTORY="$SANDBOX/image-data"
  export INPUT_VOLUME_FS="$IN"
  export OUTPUT_VOLUME_FS="$OUT"
}

# Everything the orchestrator requires of the mounted input volume.
seed_required_inputs() {
  printf '{"name":"@ondewo/nlu-client-angular","version":"7.1.2"}\n' > "$IN/package.json"
  printf '# npm readme\n'    > "$IN/README.md"
  mkdir -p "$IN/.github"
  printf '# github readme\n' > "$IN/.github/README.md"
  printf '# release\n'       > "$IN/RELEASE.md"
}

# A library generated by an earlier, successful run, sitting in the output volume.
seed_previous_library() {
  mkdir -p "$OUT/npm" "$OUT/api/ondewo" "$OUT/fesm2022"
  printf 'PREVIOUS package.json\n'   > "$OUT/package.json"
  printf 'PREVIOUS public-api.ts\n'  > "$OUT/public-api.ts"
  printf 'PREVIOUS public-api.d.ts\n' > "$OUT/public-api.d.ts"
  printf 'PREVIOUS npm manifest\n'   > "$OUT/npm/package.json"
  printf 'PREVIOUS stub\n'           > "$OUT/api/ondewo/session.pb.ts"
  printf 'PREVIOUS bundle\n'         > "$OUT/fesm2022/ondewo-nlu-client-angular.mjs"
}

assert_previous_library_intact() {
  grep -Fq 'PREVIOUS package.json'    "$OUT/package.json"
  grep -Fq 'PREVIOUS public-api.ts'   "$OUT/public-api.ts"
  grep -Fq 'PREVIOUS public-api.d.ts' "$OUT/public-api.d.ts"
  grep -Fq 'PREVIOUS npm manifest'    "$OUT/npm/package.json"
  grep -Fq 'PREVIOUS stub'            "$OUT/api/ondewo/session.pb.ts"
  grep -Fq 'PREVIOUS bundle'          "$OUT/fesm2022/ondewo-nlu-client-angular.mjs"
}

# ---------------------------------------------------------------------------
# an aborted run must not have deleted the library it was going to replace
# ---------------------------------------------------------------------------

@test "angular wipe: a missing input requirement aborts with the previous library intact" {
  # README.md is checked by the orchestrator itself - the first thing that can abort a run.
  seed_required_inputs
  rm -f "$IN/README.md"
  seed_previous_library
  stage

  run bash ./compile-proto-2-angular.sh ondewo-nlu-api ondewo
  echo "$output"
  [ "$status" -ne 0 ]
  [[ "$output" == *"README.md"* ]]
  assert_previous_library_intact
}

@test "angular wipe: a protos directory that does not exist aborts with the previous library intact" {
  seed_required_inputs
  seed_previous_library
  stage

  run bash ./compile-proto-2-angular.sh does-not-exist ondewo
  echo "$output"
  [ "$status" -ne 0 ]
  [[ "$output" == *"does not exist"* ]]
  assert_previous_library_intact
}

@test "angular wipe: a typo'd target sub-directory aborts with the previous library intact" {
  # `ondweo` instead of `ondewo`: the protos root is fine, the selected sub-directory is not.
  seed_required_inputs
  seed_previous_library
  stage

  run bash ./compile-proto-2-angular.sh ondewo-nlu-api ondweo
  echo "$output"
  [ "$status" -ne 0 ]
  assert_previous_library_intact
}

@test "angular wipe: an empty protos directory aborts with the previous library intact" {
  seed_required_inputs
  seed_previous_library
  mkdir -p "$IN/ondewo-nlu-api/empty"
  stage

  run bash ./compile-proto-2-angular.sh ondewo-nlu-api empty
  echo "$output"
  [ "$status" -ne 0 ]
  [[ "$output" == *"No proto files were found"* ]]
  assert_previous_library_intact
}

@test "angular wipe: a failing library build aborts with the previous library intact" {
  # The last thing that can fail: stubs are generated, ng-packagr (npm run build) then dies.
  # Nothing has been copied to the output volume at that point, so the previous library is
  # still the only one the client has.
  seed_required_inputs
  seed_previous_library
  stage
  export NPM_MOCK_RC=1

  run bash ./compile-proto-2-angular.sh ondewo-nlu-api ondewo
  echo "$output"
  [ "$status" -ne 0 ]
  # the run really did get past stub generation
  [ -f "$PROTOC_MOCK_LOG" ]
  assert_previous_library_intact
}

# ---------------------------------------------------------------------------
# the mounted input volume is never modified
# ---------------------------------------------------------------------------

@test "angular wipe: a successful run does not delete the input volume's node_modules" {
  # `src/node_modules` was wiped with the working directory set to the output volume, so it hit
  # the client's own installed dependencies inside the mounted input tree.
  seed_required_inputs
  mkdir -p "$IN/node_modules/@angular/core"
  printf 'INSTALLED DEPENDENCY\n' > "$IN/node_modules/@angular/core/package.json"
  stage

  run bash ./compile-proto-2-angular.sh ondewo-nlu-api ondewo
  echo "$output"
  [ "$status" -eq 0 ]
  [ -d "$IN/node_modules/@angular/core" ]
  grep -Fq 'INSTALLED DEPENDENCY' "$IN/node_modules/@angular/core/package.json"
}

@test "angular wipe: a successful run leaves the whole mounted input volume unchanged" {
  seed_required_inputs
  mkdir -p "$IN/node_modules/.bin" "$IN/auth"
  printf 'INSTALLED DEPENDENCY\n' > "$IN/node_modules/.bin/ng"
  printf "export * from './token';\n" > "$IN/auth/index.ts"
  stage

  local before after
  before=$(cd "$IN" && find . | sort | while IFS= read -r entry; do
    if [ -f "$entry" ]; then echo "$entry $(cksum <"$entry")"; else echo "$entry"; fi
  done)

  run bash ./compile-proto-2-angular.sh ondewo-nlu-api ondewo
  echo "$output"
  [ "$status" -eq 0 ]

  after=$(cd "$IN" && find . | sort | while IFS= read -r entry; do
    if [ -f "$entry" ]; then echo "$entry $(cksum <"$entry")"; else echo "$entry"; fi
  done)
  echo "--- before"; echo "$before"
  echo "--- after";  echo "$after"
  [ "$before" = "$after" ]
}

# ---------------------------------------------------------------------------
# a successful run still cleans the stale library (the clean was moved, not dropped)
# ---------------------------------------------------------------------------

@test "angular wipe: a successful run sweeps every stale entry of the previous library" {
  seed_required_inputs
  seed_previous_library
  # the entries a successful run does NOT regenerate: they exist only if the clean ran
  mkdir -p "$OUT/bundles" "$OUT/esm2015" "$OUT/fesm2015" "$OUT/esm2022" "$OUT/node_modules"
  printf 'STALE\n' > "$OUT/bundles/old.umd.js"
  printf 'STALE\n' > "$OUT/esm2015/old.js"
  printf 'STALE\n' > "$OUT/fesm2015/old.js"
  printf 'STALE\n' > "$OUT/esm2022/old.mjs"
  printf 'STALE\n' > "$OUT/node_modules/old.json"
  printf 'STALE\n' > "$OUT/ondewo-vtsi-client-angular.d.ts"
  printf 'STALE\n' > "$OUT/ondewo-vtsi-client-angular.metadata.json"
  printf 'STALE\n' > "$OUT/ondewo-vtsi-client-angular.d.ts.map"
  mkdir -p "$OUT/npm/api/ondewo"
  printf 'STALE\n' > "$OUT/npm/api/ondewo/gone.pb.ts"
  stage

  run bash ./compile-proto-2-angular.sh ondewo-nlu-api ondewo
  echo "$output"
  [ "$status" -eq 0 ]

  local stale
  for stale in bundles esm2015 fesm2015 esm2022 fesm2022 node_modules \
    ondewo-vtsi-client-angular.d.ts ondewo-vtsi-client-angular.metadata.json \
    ondewo-vtsi-client-angular.d.ts.map; do
    echo "still present: $stale"
    [ ! -e "$OUT/$stale" ]
  done
  # api/ and npm/api/ are replaced wholesale, so a stub of a deleted proto is gone too
  [ ! -e "$OUT/api/ondewo/session.pb.ts" ]
  [ ! -e "$OUT/npm/api/ondewo/gone.pb.ts" ]
  # and the regenerated library really is there
  [ -f "$OUT/api/mock_pb.ts" ]
  [ -f "$OUT/npm/public-api.ts" ]
  grep -Fq "export * from './api/mock_pb';" "$OUT/public-api.ts"
  run grep -Fq 'PREVIOUS' "$OUT/public-api.ts"
  [ "$status" -ne 0 ]
}

@test "angular wipe: with no output volume mounted the results still land in sourcevolume/lib" {
  # The clean moved down together with this fallback; it still resolves before the copy-back.
  seed_required_inputs
  stage
  export OUTPUT_VOLUME_FS="$SANDBOX/never-mounted"

  run bash ./compile-proto-2-angular.sh ondewo-nlu-api ondewo
  echo "$output"
  [ "$status" -eq 0 ]
  [[ "$output" == *"creating output in sourcevolume/lib directory"* ]]
  [ -f "$IN/lib/api/mock_pb.ts" ]
  [ -f "$IN/lib/public-api.ts" ]
  [ -f "$IN/lib/npm/public-api.ts" ]
}

# ---------------------------------------------------------------------------
# what the clean is able to reach, pinned statically
# ---------------------------------------------------------------------------

@test "angular wipe: no rm in the orchestrator takes a path relative to the working directory" {
  # The fourteen-entry clean used to `cd` into the output volume and delete relative names, which
  # is how a nested entry (`src/node_modules`) reached into the mounted input volume unnoticed.
  # Every rm path is rooted in a variable now, so what it deletes is readable at the call site.
  local offenders
  offenders=$(awk '$1 == "rm" {
      for (i = 2; i <= NF; i++) {
        if ($i ~ /^-/) continue
        if ($i !~ /^"\$/) { print FNR ": " $0; break }
      }
    }' "$ORCH")
  echo "$offenders"
  [ -z "$offenders" ]
}

@test "angular wipe: every rm of an output-volume path carries the \${VAR:?} guard" {
  # Same guard nodejs and the six targets hardened in 5.15.0 use: an empty variable must never
  # expand a deletion into the container root.
  local offenders
  offenders=$(awk '$1 == "rm" && /OUTPUT_VOLUME_FS/ && !/OUTPUT_VOLUME_FS:[?]/ { print FNR ": " $0 }' "$ORCH")
  echo "$offenders"
  [ -z "$offenders" ]
}

@test "angular wipe: the clean is ordered after the compilation steps" {
  # The ordering is the fix for the abort cases above; assert it on the script itself so a future
  # edit cannot quietly move the clean back above the requirement checks.
  local clean_line compile_line copy_line
  clean_line=$(awk '/Clean output volume/ { print FNR; exit }' "$ORCH")
  compile_line=$(awk '/compile-stubs-2-lib.sh/ { print FNR; exit }' "$ORCH")
  copy_line=$(awk '/Copying output files to mounted directory/ { print FNR; exit }' "$ORCH")
  echo "clean=$clean_line compile=$compile_line copy=$copy_line"
  [ -n "$clean_line" ] && [ -n "$compile_line" ] && [ -n "$copy_line" ]
  [ "$clean_line" -gt "$compile_line" ]
  [ "$clean_line" -lt "$copy_line" ]
}
