#!/usr/bin/env bats
# Hardening guard for the nodejs target, closing the gap between it and the six
# targets added in 5.15.0.
#
# Three bug classes, all of which made the pipeline produce a WRONG library
# while exiting 0:
#   * `find … -iname "*.proto"` with no `-type f`, so a DIRECTORY whose name ends
#     in .proto satisfied the no-protos guard and was then handed to protoc as an
#     input file (compile-proto-2-stubs.sh), or was `cat`ed while collecting
#     imports (compile-proto-2-nodejs.sh). The generated-stub count had the same
#     hole on the output side.
#   * the import scan iterated `for protofile in $(find …)`, so a proto below a
#     directory with a SPACE in its name was split into fragments, none of which
#     could be read - every google/ import it declares vanished from
#     proto-deps.txt and the dependency protos were never compiled.
#   * the sibling google/ tree was walked without checking that it exists. A
#     proto set that ships none (the target's own example/protos is one) got a
#     bare `find: …: No such file or directory` on stderr - which reads like a
#     build failure - while the run carried on, and nothing said the dependency
#     scan had been skipped.
#
# No Docker: the container paths are redirected with the scripts' own env knobs
# and protoc / grpc_tools_node_protoc / npm are PATH-mocked.

load 'helpers/setup'

setup() {
  common_setup
  export PROTOC_MOCK_LOG="$SANDBOX/protoc.log"
  export NPM_MOCK_LOG="$SANDBOX/npm.log"
  IN="$SANDBOX/input"
  OUT="$SANDBOX/output"
  mkdir -p "$IN" "$OUT"
  printf '{"name":"fixture","version":"0.0.1"}\n' > "$IN/package.json"
}
teardown() { common_teardown; }

# write_proto <path> [import …]: a minimal proto declaring the given imports.
write_proto() {
  local target=$1 imported
  shift
  mkdir -p "$(dirname "$target")"
  {
    printf 'syntax = "proto3";\n'
    for imported in "$@"; do printf 'import "%s";\n' "$imported"; done
    printf 'message T {}\n'
  } > "$target"
}

# stage: copy nodejs/image-data into the sandbox (nothing is written into the
# repo tree), cd there - the orchestrator invokes its siblings as ./x.sh - and
# point the container-path knobs at the sandbox.
stage() {
  cp -r "$REPO_ROOT/nodejs/image-data" "$SANDBOX/image-data"
  cd "$SANDBOX/image-data"
  export IMAGE_DATA_DIRECTORY="$SANDBOX/image-data"
  export INPUT_VOLUME_FS="$IN"
  export OUTPUT_VOLUME_FS="$OUT"
  DEPS_FILE="$SANDBOX/image-data/src/proto-deps.txt"
}

# run_stubs <protos dir> <deps file>: drive compile-proto-2-stubs.sh directly.
run_stubs() {
  run bash "$REPO_ROOT/nodejs/image-data/compile-proto-2-stubs.sh" \
    "$SANDBOX/stubs" "$1" "$1" "$2"
}

# ---------------------------------------------------------------------------
# compile-proto-2-stubs.sh - the entry set and the generated-stub count
# ---------------------------------------------------------------------------

@test "node-h1: the no-protos guard is not satisfied by a DIRECTORY named *.proto" {
  mkdir -p "$IN/protos/vendor.proto"
  : > "$SANDBOX/deps.txt"
  run_stubs "$IN/protos" "$SANDBOX/deps.txt"
  echo "$output"
  [ "$status" -eq 1 ]
  [[ "$output" == *"but are required to build a library from"* ]]
}

@test "node-h2: a DIRECTORY named *.proto is never handed to protoc as an input file" {
  mkdir -p "$IN/protos/vendor.proto"
  write_proto "$IN/protos/test.proto"
  : > "$SANDBOX/deps.txt"
  run_stubs "$IN/protos" "$SANDBOX/deps.txt"
  echo "$output"
  [ "$status" -eq 0 ]
  # the real proto is compiled ...
  run grep -Fq "/protos/test.proto" "$PROTOC_MOCK_LOG"
  [ "$status" -eq 0 ]
  # ... and the directory is not passed as an input file (real protoc fails on it
  # with its own error instead of this script's named one)
  run grep -Fq "/protos/vendor.proto" "$PROTOC_MOCK_LOG"
  [ "$status" -ne 0 ]
}

@test "node-h3: the generated-stub count ignores a DIRECTORY named *.d.ts" {
  write_proto "$IN/protos/test.proto"
  : > "$SANDBOX/deps.txt"
  mkdir -p "$SANDBOX/stubs/legacy.d.ts"
  run_stubs "$IN/protos" "$SANDBOX/deps.txt"
  echo "$output"
  [ "$status" -eq 0 ]
  # exactly the one .ts FILE the ts_out pass wrote (mock_pb.d.ts)
  [[ "$output" == *"files generated by proto compilation: 1"* ]]
}

# ---------------------------------------------------------------------------
# compile-proto-2-nodejs.sh - the google dependency scan
# ---------------------------------------------------------------------------

@test "node-h4: a missing sibling google/ directory is reported, not a bare find error" {
  # the target's own example ships protos/ without a google/ sibling
  write_proto "$IN/protos/library/test.proto" "google/protobuf/empty.proto"
  stage
  run bash ./compile-proto-2-nodejs.sh protos library
  echo "$output"
  [ "$status" -eq 0 ]
  [[ "$output" == *"skipping the google dependency scan"* ]]
  [[ "$output" != *"No such file or directory"* ]]
}

@test "node-h5: a DIRECTORY named *.proto in the compiled tree is not read as a proto" {
  write_proto "$IN/protos/library/test.proto" "google/protobuf/empty.proto"
  mkdir -p "$IN/protos/library/vendor.proto"
  stage
  run bash ./compile-proto-2-nodejs.sh protos library
  echo "$output"
  [ "$status" -eq 0 ]
  [[ "$output" != *"Is a directory"* ]]
  # the real proto is still scanned, so its google import reaches the deps file
  run grep -Fq "google/protobuf/empty.proto" "$DEPS_FILE"
  [ "$status" -eq 0 ]
}

@test "node-h6: a DIRECTORY named *.proto under google/ is not read as a proto" {
  write_proto "$IN/protos/library/test.proto"
  mkdir -p "$IN/protos/google/api/annotations.proto"
  stage
  run bash ./compile-proto-2-nodejs.sh protos library
  echo "$output"
  [ "$status" -eq 0 ]
  [[ "$output" != *"Is a directory"* ]]
}

@test "node-h7: a proto below a directory with a space still contributes its google imports" {
  write_proto "$IN/protos/lib rary/test.proto" "google/protobuf/empty.proto"
  stage
  run bash ./compile-proto-2-nodejs.sh protos "lib rary"
  echo "$output"
  [ "$status" -eq 0 ]
  [[ "$output" != *"No such file or directory"* ]]
  # the import is collected ...
  run grep -Fq "google/protobuf/empty.proto" "$DEPS_FILE"
  [ "$status" -eq 0 ]
  # ... and the dependency proto it names is actually compiled
  run grep -Fq "google/protobuf/empty.proto" "$PROTOC_MOCK_LOG"
  [ "$status" -eq 0 ]
}

@test "node-h8: the google tree is still scanned for transitive imports" {
  write_proto "$IN/protos/library/test.proto" "google/protobuf/empty.proto"
  write_proto "$IN/protos/google/api/annotations.proto" "google/protobuf/descriptor.proto"
  stage
  run bash ./compile-proto-2-nodejs.sh protos library
  echo "$output"
  [ "$status" -eq 0 ]
  [[ "$output" == *"Google: For loop:"* ]]
  run grep -Fq "google/protobuf/descriptor.proto" "$DEPS_FILE"
  [ "$status" -eq 0 ]
}

@test "node-h9: the google exclusion list still keeps the ignored trees out" {
  write_proto "$IN/protos/library/test.proto" "google/protobuf/empty.proto"
  write_proto "$IN/protos/google/api/annotations.proto" "google/protobuf/descriptor.proto"
  # matches the include filter ("api") but is excluded by "vision"
  write_proto "$IN/protos/google/vision/api.proto" "google/protobuf/struct.proto"
  stage
  run bash ./compile-proto-2-nodejs.sh protos library
  echo "$output"
  [ "$status" -eq 0 ]
  run grep -Fq "google/protobuf/struct.proto" "$DEPS_FILE"
  [ "$status" -ne 0 ]
  run grep -Fq "google/protobuf/struct.proto" "$PROTOC_MOCK_LOG"
  [ "$status" -ne 0 ]
}
