#!/bin/bash
set -e

STUBS_TARGET_DIR=$1
PROTOS_ROOT_DIR=$2
PROTOS_SRC_DIR=$3
PROTOS_DEPS_FILE=$4

echo "Make proto generation target directory: $STUBS_TARGET_DIR"
mkdir -p "$STUBS_TARGET_DIR"

#Find .protos in directory and count the occurances
echo "Checking $PROTOS_SRC_DIR for .proto files"
if [ ! -d "$PROTOS_SRC_DIR" ]; then
    echo "ERROR: No proto files were found - the protos source directory '$PROTOS_SRC_DIR' does not exist - exiting" >&2
    exit 1
fi
#Matched by NAME and then filtered with `test -f` - never with find's own `-type f`. This is the
#`[ -f ]` filter angular/ and go/ apply, written in find's own syntax so that a path containing a
#newline stays a single entry instead of being re-split by a shell loop:
#  * `-type f` does not follow a symlink, and the input volume is staged with `cp -r`, which
#    keeps links verbatim - so a .proto a client symlinked into its protos dir was silently
#    dropped from the compile set (measured: find -type f returns 1 of 2). `test -f` follows it.
#  * the name alone is not enough either: a DIRECTORY named e.g. "session.proto" would satisfy
#    the guard below and then be handed to protoc as a positional input, where it fails with
#    "Is a directory" instead of the script's own "no proto files" message.
#  * NOT `find -L ... -type f`: that spelling has to put the flag BEFORE the start path, which
#    the BSD-portability gate over these scripts rejects, and -L makes find DESCEND into
#    symlinked directories, where a link loop can hang the run. Plain find never descends one,
#    so a looping link is just a link that fails `test -f` and is reported by the guard below.
#Resolved ONCE and reused as both the count and the protoc argument list: running find twice is
#what lets the guard and the compile pass disagree about what a .proto is.
ALL_PROTO_FILES=$(find "$PROTOS_SRC_DIR" -iname "*.proto" -exec test -f {} \; -print)
#A .proto symlink that resolves to nothing (or to a directory) drops out of the set above without
#a word - and a silently missing proto is a silently missing service in the client. `sed`+`tr`
#join the hits onto the message line exactly the way angular/ and go/ spell it.
DANGLING_PROTO_LINKS=$(find "$PROTOS_SRC_DIR" -type l -iname "*.proto" -exec test ! -f {} \; -print | sed 's|^| |' | tr -d '\n')
if [ -n "$DANGLING_PROTO_LINKS" ]; then
    echo "ERROR: these .proto symlinks do not resolve to a file:$DANGLING_PROTO_LINKS" >&2
    echo "       the mounted input volume is staged with 'cp -r', which keeps symlinks verbatim, so a link that leaves that volume (an absolute path, or a relative one reaching above it) dangles in the copy - point it inside the mounted directory or materialise the file - exiting" >&2
    exit 1
fi
PROTO_FILES_CNT=$(printf '%s\n' "$ALL_PROTO_FILES" | grep -c . || true)
if [[ $PROTO_FILES_CNT -lt 1 ]]; then
    echo "ERROR: No proto files were found in the '$PROTOS_SRC_DIR' directory, but are required to build a library from - exiting"
    exit 1
fi
echo "Found $PROTO_FILES_CNT .proto files in directory: $PROTOS_SRC_DIR"
echo "Source verified."

# -------------- Generate the proto client library stubs
echo "Starting .proto to grpc client stubs compilation ..."
echo "Consuming .proto files: $ALL_PROTO_FILES: "

# shellcheck disable=SC2086  # intentional word splitting of proto file list
protoc \
--js_out=import_style=commonjs,binary:"$STUBS_TARGET_DIR" \
--grpc-web_out=import_style=commonjs+dts,mode=grpcweb:"$STUBS_TARGET_DIR" \
-I "$PROTOS_ROOT_DIR" \
$ALL_PROTO_FILES

# Only build dependency protos when the deps file actually lists some. An empty
# (or whitespace-only) file would expand to zero args and invoke protoc with no
# input files, which fails ("Missing input file.") and, under set -e, would
# otherwise abort the whole build for proto sets that have no google/ imports.
if [ -f "$PROTOS_DEPS_FILE" ] && grep -q '[^[:space:]]' "$PROTOS_DEPS_FILE"; then
    echo "Proto dependencies file was specified -> building protos for dependencies"
    PROTO_DEPS=$(cat "$PROTOS_DEPS_FILE")
    PROTO_DEPS_FILES_CNT=$(grep -c . "$PROTOS_DEPS_FILE" || true)

    echo "Found $PROTO_DEPS_FILES_CNT .proto files in dependencies file proto-deps.txt"

    # shellcheck disable=SC2086  # intentional word splitting of proto file list
    protoc \
    --js_out=import_style=commonjs,binary:"$STUBS_TARGET_DIR" \
    --grpc-web_out=import_style=commonjs+dts,mode=grpcweb:"$STUBS_TARGET_DIR" \
    -I "$PROTOS_ROOT_DIR" \
    $PROTO_DEPS
fi


echo ".proto compilation finished."

#`-type f` for the same reason as the entry-proto scan above: a DIRECTORY named "*.ts" is not a
#generated stub and must not inflate the reported count.
STUB_FILES_CNT=$(find "$STUBS_TARGET_DIR" -type f -iname "*.ts" | grep -c . || true)
echo "files generated by proto compilation: $STUB_FILES_CNT"
#...and the number is ACTED ON, not just printed: protoc exits 0 on an input set it generated
#nothing from, and the empty api/ then travels through the barrel generation and the copy-back
#into the client repo, whose previously generated api/ the orchestrator wipes on the way.
if [ "$STUB_FILES_CNT" -lt 1 ]; then
    echo "ERROR: protoc reported success but produced no '*.ts' sources in '$STUBS_TARGET_DIR' - there is nothing to build a library from - exiting" >&2
    exit 1
fi
