#!/bin/bash
set -e

STUBS_TARGET_DIR=$1
PROTOS_ROOT_DIR=$2
PROTOS_SRC_DIR=$3
PROTOS_DEPS_FILE=$4

echo "Make proto generation target directory: $STUBS_TARGET_DIR"
mkdir -p "$STUBS_TARGET_DIR"

#Find .protos in directory and count the occurances
echo "Checking $PROTOS_SRC_DIR for .proto files"
if [ ! -d "$PROTOS_SRC_DIR" ]; then
    echo "ERROR: No proto files were found - the protos source directory '$PROTOS_SRC_DIR' does not exist - exitting" >&2
    exit 1
fi
ALL_PROTO_FILES=$(find "$PROTOS_SRC_DIR" -iname "*.proto")
# grep -c returns 1 (and would trip set -e) on an empty list; || true lets the guard below report it
PROTO_FILES_CNT=$(printf '%s\n' "$ALL_PROTO_FILES" | grep -c . || true)
if [[ $PROTO_FILES_CNT -lt 1 ]]; then
    echo "ERROR: No proto files were found in the '$PROTOS_SRC_DIR' directory, but are required to build a library from - exitting"
    exit 1
fi
echo "Found $PROTO_FILES_CNT .proto files in directory: $PROTOS_SRC_DIR"
echo "Source verified."

# -------------- Generate the proto client library stubs
echo "Starting .proto to grpc client stubs compilation ..."
echo "Consuming .proto files: $ALL_PROTO_FILES: "

# generate js codes via grpc-tools
# shellcheck disable=SC2086  # intentional word splitting of proto file list
grpc_tools_node_protoc \
"--js_out=import_style=commonjs,binary:$STUBS_TARGET_DIR" \
"--grpc_out=grpc_js:$STUBS_TARGET_DIR" \
-I "$PROTOS_ROOT_DIR" \
$ALL_PROTO_FILES

# generate d.ts codes
# shellcheck disable=SC2086  # intentional word splitting of proto file list
protoc \
--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
"--ts_out=$STUBS_TARGET_DIR" \
-I "$PROTOS_ROOT_DIR" \
$ALL_PROTO_FILES


# Only build dependency protos when the deps file actually lists some. An empty
# (or whitespace-only) file would expand to zero args and invoke protoc with no
# input files, which fails ("Missing input file.") and, under set -e, would
# otherwise abort the whole build for proto sets that have no google/ imports.
if [ -f "$PROTOS_DEPS_FILE" ] && grep -q '[^[:space:]]' "$PROTOS_DEPS_FILE"; then
    echo "Proto dependencies file was specified -> building protos for dependencies"
    PROTO_DEPS=$(cat "$PROTOS_DEPS_FILE")
    PROTO_DEPS_FILES_CNT=$(grep -c . "$PROTOS_DEPS_FILE" || true)

    echo "Found $PROTO_DEPS_FILES_CNT .proto files in dependencies file proto-deps.txt"

    # generate js codes via grpc-tools
    # shellcheck disable=SC2086  # intentional word splitting of proto file list
    grpc_tools_node_protoc \
    "--js_out=import_style=commonjs,binary:$STUBS_TARGET_DIR" \
    "--grpc_out=grpc_js:$STUBS_TARGET_DIR" \
    -I "$PROTOS_ROOT_DIR" \
    $PROTO_DEPS

    # generate d.ts codes
    # shellcheck disable=SC2086  # intentional word splitting of proto file list
    protoc \
    --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
    "--ts_out=$STUBS_TARGET_DIR" \
    -I "$PROTOS_ROOT_DIR" \
    $ALL_PROTO_FILES \
    $PROTO_DEPS
fi


echo ".proto compilation finished."

STUB_FILES_CNT=$(find "$STUBS_TARGET_DIR" -iname "*.ts" | grep -c . || true)
echo "files generated by proto compilation: $STUB_FILES_CNT"
