#!/bin/bash
. "$(dirname "$0")"/dependecy-resolver.sh

STUBS_TARGET_DIR="$1"
PROTOS_ROOT_DIR="$2"
PROTOS_SRC_DIR="$3"

#Exit on error
set -e

echo "Stubs target dir: $STUBS_TARGET_DIR"
echo "Protos root dir: $PROTOS_ROOT_DIR"
echo "Protos src dir: $PROTOS_SRC_DIR"

#Find .protos in directory and count the occurances
echo "Checking $PROTOS_SRC_DIR for .proto files"

if [ ! -d "$PROTOS_SRC_DIR" ]; then
    echo "ERROR: No proto files were found - the protos source directory '$PROTOS_SRC_DIR' does not exist - exitting" >&2
    exit 1
fi
ENTRY_PROTO_FILES=$(find "$PROTOS_SRC_DIR" -iname "*.proto")
if [ -z "$ENTRY_PROTO_FILES" ]; then
    echo "ERROR: No proto files were found in the '/protos' directory, but are required to build a library from - exitting" >&2
    exit 1
fi
PROTO_FILES_CNT=$(printf '%s\n' "$ENTRY_PROTO_FILES" | grep -c .)
echo "Found $PROTO_FILES_CNT .proto files in directory: $PROTOS_SRC_DIR"
echo "Source verified."

#ONE_FILE=$(echo "$ENTRY_PROTO_FILES" | head -n 1)
#echo "$ONE_FILE"
#ALL_PROTO_FILES=$(echoProtoDependencies "$PROTOS_ROOT_DIR" "$ONE_FILE")
export -f echoDependencies
export -f echoProtoDependencies
#echo "$ENTRY_PROTO_FILES" | xargs -I % bash -c "$(echoProtoDependencies "$PROTOS_ROOT_DIR" "%")"
#ALL_PROTO_FILES=$(echo "$ENTRY_PROTO_FILES" | xargs -I % bash -c "echoProtoDependencies \"$PROTOS_ROOT_DIR\" %" | tac | tr "\n" " ")
#ALL_PROTO_FILES=$(echoProtoDependencies "$ENTRY_PROTO_FILES" "$PROTOS_ROOT_DIR" | tac | tr "\n" " ")
if ! ALL_PROTO_FILES=$(echoProtoDependencies "$PROTOS_ROOT_DIR" "$ENTRY_PROTO_FILES"); then
    echo "Dependency resolution failed" >&2
    exit 1
fi
ALL_PROTO_FILES=$(printf '%s\n' "$ALL_PROTO_FILES" | sort -u | tr "\n" " ")
#ALL_PROTO_FILES=$(printf "%s\n%s" "$ENTRY_PROTO_FILES" "$ALL_PROTO_FILES")
# tr -d strips BSD/macOS wc's leading-space field padding (GNU wc emits a bare count)
ALL_PROTO_FILES_CNT=$(echo "$ALL_PROTO_FILES" | wc -w | tr -d ' ')

# -------------- Generate the proto client library stubs
echo "Starting .proto to grpc client stubs compilation ..."
echo "Consuming $ALL_PROTO_FILES_CNT .proto files: $ALL_PROTO_FILES ... "

mkdir -p "$STUBS_TARGET_DIR"

echo "Target dir: $STUBS_TARGET_DIR"
echo "Root dir: $PROTOS_ROOT_DIR"
printf "Files to compile: \n%s\n\n" "$ALL_PROTO_FILES"

CWD=$(pwd)

cd "$PROTOS_ROOT_DIR"

#mode=grpcwebtext mode=grpcweb
# shellcheck disable=SC2086  # intentional word splitting of proto file list
protoc \
--js_out=import_style=commonjs,binary:"$STUBS_TARGET_DIR" \
--grpc-web_out=import_style=commonjs,mode=grpcwebtext:"$STUBS_TARGET_DIR" \
-I "$PROTOS_ROOT_DIR" \
$ALL_PROTO_FILES

echo ""

#protoc \
#--js_out=import_style=commonjs,binary:"$STUBS_TARGET_DIR" \
#--grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:"$STUBS_TARGET_DIR" \
#-I "$PROTOS_ROOT_DIR" \
#"$ALL_PROTO_FILES"

echo ".proto compilation finished."

cd "$CWD"


# tr -d strips BSD/macOS wc's leading-space field padding (GNU wc emits a bare count)
STUB_FILES_CNT=$(find "$STUBS_TARGET_DIR" -iname "*.js" | wc -l | tr -d ' ')
echo "files generated by proto compilation: $STUB_FILES_CNT"
