#!/bin/bash
set -e

# -------------- Compile the generated stubs into a real, installable library.
# This is the step that makes the cpp target a FULL PACKAGED LIBRARY rather than a stub dump: it
# compiles every generated *.pb.cc / *.grpc.pb.cc with the image's g++ and installs a static
# archive plus the public headers and a consumable CMake package.

#Root directory of the compilation -> CMakeLists.txt + public-api.h + the generated stubs in api/
SRC_DIRECTORY=$1
#CMake target / package / archive name; injected into the generic CMakeLists.txt via -D
LIBRARY_NAME=$2

if [ -z "$SRC_DIRECTORY" ] || [ -z "$LIBRARY_NAME" ]; then
    echo "ERROR: usage: compile-stubs-2-lib.sh <src_directory> <library_name> - exiting" >&2
    exit 1
fi
if [ ! -d "$SRC_DIRECTORY" ]; then
    echo "ERROR: the source directory '$SRC_DIRECTORY' does not exist - exiting" >&2
    exit 1
fi
if [ ! -f "$SRC_DIRECTORY/CMakeLists.txt" ]; then
    echo "ERROR: no CMakeLists.txt in '$SRC_DIRECTORY' - the default build file was neither shipped by the input volume nor copied in - exiting" >&2
    exit 1
fi

echo "Starting cpp build process of library package ..."

#Container defaults; env-overridable so the script can run (and be tested) outside the image.
#The build and install trees live outside $SRC_DIRECTORY on purpose - see compile-proto-2-cpp.sh.
IMAGE_DATA_DIRECTORY="${IMAGE_DATA_DIRECTORY:-/image-data}"
BUILD_DIRECTORY="${BUILD_DIRECTORY:-$IMAGE_DATA_DIRECTORY/build}"
INSTALL_DIRECTORY="${INSTALL_DIRECTORY:-$IMAGE_DATA_DIRECTORY/install}"

#Version stamped into project(VERSION ...) and <name>-config-version.cmake. ONDEWO_CLIENT_VERSION
#is set by the Dockerfile from ARG LIB_VERSION (= ONDEWO_PROTO_COMPILER_VERSION).
LIBRARY_VERSION="${ONDEWO_CLIENT_VERSION:-0.0.0}"

#CMake's project(VERSION) and write_basic_package_version_file() only accept a dotted numeric
#version; a pre-release suffix such as 5.15.0-rc1 aborts the configure step with a CMake error
#wall. Catch it here with a message that says what to do about it.
case "$LIBRARY_VERSION" in
    *[!0-9.]*|''|.*|*.)
        echo "ERROR: library version '$LIBRARY_VERSION' is not a dotted numeric version - CMake's project(VERSION ...) requires MAJOR.MINOR.PATCH (no pre-release suffix); set ONDEWO_CLIENT_VERSION accordingly - exiting" >&2
        exit 1
        ;;
esac

command -v cmake >/dev/null 2>&1 || {
    echo "ERROR: cmake not found on PATH - the generated stubs cannot be compiled into a library; is the image's build toolchain installed? - exiting" >&2
    exit 1
}

#Count ONLY what this run generated: the stubs live in $SRC_DIRECTORY/api, which is also the one
#tree the CMakeLists globs. $SRC_DIRECTORY itself is a verbatim copy of the input volume, so
#searching it whole would let any *.pb.cc a client happens to vendor (checked-in stubs, a sample,
#a previous run's output kept in src/lib/) satisfy this guard while api/ is empty - exactly the
#"produced nothing to build" case it exists to catch.
#`-type f` so a DIRECTORY named "*.pb.cc" cannot satisfy it either, and
#`grep -c . || true` instead of `wc -l`: BSD/macOS wc pads its output with spaces.
STUB_SOURCES_CNT=0
if [ -d "$SRC_DIRECTORY/api" ]; then
    STUB_SOURCES_CNT=$(find "$SRC_DIRECTORY/api" -type f -name "*.pb.cc" | grep -c . || true)
fi
if [ "$STUB_SOURCES_CNT" -lt 1 ]; then
    echo "ERROR: no generated '*.pb.cc' sources under '$SRC_DIRECTORY/api' - the .proto compilation step produced nothing to build - exiting" >&2
    exit 1
fi

#getconf, not nproc: nproc is a GNU coreutils extension and the test suite also runs on the
#macos-latest CI leg, where nproc does not exist. CMAKE_BUILD_PARALLEL_LEVEL is the escape hatch
#for small Docker VMs - each cc1plus on a large generated .pb.cc needs a few hundred MB of RAM, so
#under ~4 GB set it to 2-4 to avoid a confusing "c++: fatal error: Killed signal terminated cc1plus".
BUILD_JOBS="${CMAKE_BUILD_PARALLEL_LEVEL:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)}"

#Always configure into a FRESH build tree: the CMakeLists discovers the stubs with
#file(GLOB_RECURSE), which is evaluated at configure time, so a re-used build directory would
#silently miss stubs generated by this run. Same for the install tree - a stale artifact there
#would be copied to the output volume as if this run had produced it.
rm -rf "${BUILD_DIRECTORY:?}" "${INSTALL_DIRECTORY:?}"

echo "Compiling $STUB_SOURCES_CNT generated stub sources into '$LIBRARY_NAME' (version $LIBRARY_VERSION) with $BUILD_JOBS parallel jobs ..."

cmake -S "$SRC_DIRECTORY" -B "$BUILD_DIRECTORY" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_DIRECTORY" \
    -DONDEWO_LIBRARY_NAME="$LIBRARY_NAME" \
    -DONDEWO_LIBRARY_VERSION="$LIBRARY_VERSION" \
    || { echo "ERROR: 'cmake' configure step failed for '$SRC_DIRECTORY' - exiting" >&2; exit 1; }

cmake --build "$BUILD_DIRECTORY" --parallel "$BUILD_JOBS" \
    || { echo "ERROR: 'cmake --build' failed - the generated stubs did not compile against this image's libprotobuf/libgrpc++ - exiting" >&2; exit 1; }

#Separate from --build (rather than --target install) so the parallel build and the install stay
#independently observable and scriptable.
cmake --install "$BUILD_DIRECTORY" \
    || { echo "ERROR: 'cmake --install' failed - nothing was installed into '$INSTALL_DIRECTORY' - exiting" >&2; exit 1; }

echo "Finished cpp build. Install tree: $INSTALL_DIRECTORY"
