// This file is generated by the ondewo-rust-proto-compiler - DO NOT EDIT.
//
// It is the crate barrel: `pub mod api;` pulls in the generated prost/tonic module tree
// (src/api/mod.rs), and every hand-written module sitting beside it under src/ is declared
// below by make-lib-entry-point.sh. Without that, hand-written sources are compiled into
// the crate but unreachable from outside it.
//
// The rustdoc allows are load-bearing: the ONDEWO protos carry raw URLs and raw HTML
// anchors in their comments and prost copies those verbatim into doc comments, which
// breaks `cargo doc` and any consumer building with RUSTDOCFLAGS=-D warnings.
#![allow(clippy::all)]
#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(rustdoc::invalid_html_tags)]

pub mod api;
pub use api::*;
